name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        go: ['1.13.1']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: Go ${{ matrix.go }} test in ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Environment
        run: |
          go version
          go env

      - name: Unit Test
        run: make test

      - name: Build
        run: |
          bash build.sh

      - name: Test (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          tar -xzvf ./bin/denox_linux_amd64.tar.gz
          ./bin/denox https://deno.land/x/std/examples/welcome.ts

      - name: Test (OSX)
        if: startsWith(matrix.os, 'macOS')
        run: |
          tar -xzvf ./bin/denox_darwin_amd64.tar.gz
          ./bin/denox https://deno.land/x/std/examples/welcome.ts

      - name: Test (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
          tar -xzvf ./bin/denox_windows_amd64.tar.gz
          ./bin/denox.exe https://deno.land/x/std/examples/welcome.ts

      # after success
      - name: Coverage
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          go get golang.org/x/tools/cmd/cover
          go get github.com/mattn/goveralls
          /home/runner/go/bin/goveralls -coverprofile=coverage.out -service=github-action -repotoken ${{ secrets.COVERALLS_TOKEN }}